"""
Step 25: Multi-Provider Podcast Generation

Generate podcasts using either OpenAI or Gemini providers.
Supports hybrid configurations (e.g., Gemini LLM + OpenAI TTS).
"""

from pathlib import Path
from datetime import datetime

from providers.factory import ProviderConfig, create_llm_provider, create_tts_provider, detect_available_providers
from core.provider_setup import get_provider_info
from core.content_generation import build_script, build_show_notes, generate_audio
from core.validation import sanitize_filename, validate_choice, get_word_range
from core.user_input import get_user_input
from core.file_utils import save_text_file, read_text_file
from core.episode_management import (
    create_episode_directory,
    save_episode_metadata,
    create_episode_summary,
    update_episode_index
)
import config


def main():
    """Multi-provider podcast generation"""
    print("\n" + "="*70)
    print("Step 25: Multi-Provider Podcast Generation")
    print("="*70)

    # Detect available providers
    available = detect_available_providers()
    print("\nAvailable providers:")
    for provider, status in available.items():
        print(f"  {provider}: {'✓' if status else '✗'}")

    if not available:
        print("\n[ERROR] No providers available. Set OPENAI_API_KEY or GOOGLE_API_KEY")
        return

    # Choose providers
    llm_options = list(available.keys())
    tts_options = list(available.keys())

    print("\n--- LLM Provider Selection ---")
    for i, provider in enumerate(llm_options, 1):
        print(f"{i}. {provider}")

    llm_choice = input(f"Choose LLM provider (1-{len(llm_options)}, default 1): ").strip() or "1"
    llm_provider_name = llm_options[int(llm_choice)-1]

    print("\n--- TTS Provider Selection ---")
    for i, provider in enumerate(tts_options, 1):
        print(f"{i}. {provider}")

    tts_choice = input(f"Choose TTS provider (1-{len(tts_options)}, default 1): ").strip() or "1"
    tts_provider_name = tts_options[int(tts_choice)-1]

    print(f"\n[OK] Configuration:")
    print(f"  LLM: {llm_provider_name}")
    print(f"  TTS: {tts_provider_name}")

    # Create provider config
    provider_config = ProviderConfig(
        llm_provider=llm_provider_name,
        tts_provider=tts_provider_name
    )

    # Initialize providers
    llm_provider = create_llm_provider(provider_config)
    tts_provider = create_tts_provider(provider_config)

    print(f"\n[OK] Providers initialized:")
    print(f"  LLM: {llm_provider.provider_name} ({llm_provider.model_name})")
    print(f"  TTS: {tts_provider.provider_name} ({tts_provider.model_name})")

    # Get episode settings
    topic = input("\nEnter episode topic: ").strip()
    if not topic:
        topic = "Multi-Provider Test"

    tone = get_user_input("Choose tone (casual/professional/educational)", config.DEFAULT_TONE)
    voice = get_user_input(
        f"Choose voice ({'/'.join(tts_provider.available_voices)})",
        tts_provider.available_voices[0]
    )
    length = get_user_input("Choose length (short/medium/long)", config.DEFAULT_LENGTH)

    # Validate
    tone = validate_choice(tone, config.VALID_TONES, "tone")
    voice = validate_choice(voice, set(tts_provider.available_voices), "voice")
    length = validate_choice(length, config.VALID_LENGTHS, "length")
    word_range = get_word_range(length)

    # Create episode directory
    output_root = Path(config.OUTPUT_ROOT)
    episode_dir, episode_id = create_episode_directory(output_root, topic)

    print(f"\n[OK] Episode directory: {episode_dir}")
    print(f"[OK] Episode ID: {episode_id}")

    # Generate script
    print("\nGenerating script...")
    try:
        script = build_script(llm_provider, topic, tone, word_range)
        script_file = episode_dir / "script.txt"
        save_text_file(script, script_file)
        print(f"[OK] Script generated by {llm_provider.provider_name}")
        print(f"[OK] Script saved: {script_file.name}")
    except Exception as e:
        print(f"[ERROR] Script generation failed: {e}")
        return

    # Generate show notes
    print("\nGenerating show notes...")
    try:
        show_notes = build_show_notes(llm_provider, script)
        show_notes_file = episode_dir / "show_notes.txt"
        save_text_file(show_notes, show_notes_file)
        print(f"[OK] Show notes generated by {llm_provider.provider_name}")
    except Exception as e:
        print(f"[WARN] Show notes generation failed: {e}")
        show_notes = f"Show notes for {topic}"
        show_notes_file = episode_dir / "show_notes.txt"
        save_text_file(show_notes, show_notes_file)

    # Generate audio
    audio_file = episode_dir / f"podcast_{voice}.mp3"
    print(f"\nGenerating audio with {tts_provider.provider_name}...")
    try:
        generate_audio(tts_provider, script, voice, audio_file)
        print(f"[OK] Audio generated by {tts_provider.provider_name}")
        print(f"[OK] Audio saved: {audio_file.name}")
    except Exception as e:
        print(f"[ERROR] Audio generation failed: {e}")
        # Copy demo audio as fallback
        demo_audio = Path("output/ai_trending/podcast_nova.mp3")
        if demo_audio.exists():
            import shutil
            shutil.copy(demo_audio, audio_file)
            print(f"[OK] Demo audio copied")

    # Save metadata
    created_at = datetime.now().isoformat()
    provider_info = get_provider_info(llm_provider, tts_provider)

    metadata = {
        "created_at": created_at,
        "episode_id": episode_id,
        "topic": topic,
        "tone": tone,
        "voice": voice,
        "length": length,
        "word_range_target": word_range,
        "providers": provider_info,
        "provider_config": {
            "llm_provider": llm_provider_name,
            "tts_provider": tts_provider_name,
            "hybrid_mode": llm_provider_name != tts_provider_name
        },
        "models": {
            "script_model": llm_provider.model_name,
            "tts_model": tts_provider.model_name
        },
        "outputs": {
            "episode_dir": str(episode_dir),
            "script_file": str(script_file),
            "show_notes_file": str(show_notes_file),
            "audio_file": str(audio_file)
        }
    }

    metadata_file = save_episode_metadata(episode_dir, metadata)
    print(f"[OK] Metadata saved: {metadata_file.name}")

    # Update episode index
    episode_summary = create_episode_summary(
        metadata=metadata,
        episode_dir=episode_dir,
        additional_fields={
            "llm_provider": llm_provider_name,
            "tts_provider": tts_provider_name,
            "hybrid_mode": llm_provider_name != tts_provider_name
        }
    )

    index_file = output_root / "episode_index.json"
    update_episode_index(index_file, episode_summary)

    # Summary
    print("\n" + "="*70)
    print("Step 25 Complete: Multi-Provider Podcast")
    print("="*70)
    print(f"\nEpisode ID: {episode_id}")
    print(f"Location: {episode_dir}")
    print(f"\nProvider Configuration:")
    print(f"  LLM: {llm_provider_name} ({llm_provider.model_name})")
    print(f"  TTS: {tts_provider_name} ({tts_provider.model_name})")
    if llm_provider_name != tts_provider_name:
        print(f"  Mode: HYBRID ✓")
    print(f"\nGenerated files:")
    print(f"  - script.txt (by {llm_provider_name})")
    print(f"  - show_notes.txt")
    print(f"  - podcast_{voice}.mp3 (by {tts_provider_name})")
    print(f"  - metadata.json")


if __name__ == "__main__":
    main()
